apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-app-node
  labels:
    app: mongodb-app-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-app-node
  template:
    metadata:
      labels:
        app: mongodb-app-node
    spec:
      containers:
        - name: mongodb-app-node
          image: ahmed117/mongodb-k8s-app:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          env:
            - name: MONGO_USERNAME
              value: "{{ .spectro.app.$appDeploymentName.mongodb-community-operator-2.USERNAME }}"
            - name: MONGO_PASSWORD
              value: "{{ .spectro.app.$appDeploymentName.mongodb-community-operator-2.PASSWORD }}"
            - name: MONGO_HOST
              value: "{{ .spectro.app.$appDeploymentName.mongodb-community-operator-2.MONGO_URI_SRV }}"
            - name: FLASK_ENV
              value: "development"

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-app-node-svc
spec:
  selector:
    app: mongodb-app-node
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer